home: ${env:LYX_HOME:-Home.md} # home page file name; relative to board dir
sidebar: ${env:LYX_SIDEBAR:-_Sidebar.md} # sidebar file name; relative to board dir
proposal_prefix: s4test- # prefix for proposal files
